import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";

import 'react-loading-skeleton/dist/skeleton.css'
import {Providers} from "@/app/provider";
import ReduxProvider from "@/redux/provider";
import dynamic from "next/dynamic";
import {ToastContainer} from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const PersistedReduxProvider = dynamic(
    () => import("@/redux/provider"),
    { ssr: false }
);

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Driven License Learning',
    description: 'Generated by create next app',
}

export default function AuthenticateLayout({
                                               children,
                                           }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ReduxProvider>
            <Providers>
                <div>
                    {children}
                    <ToastContainer />
                </div>
            </Providers>
        </ReduxProvider>
        </body>
        </html>
    )
}
