import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import React from "react";

import 'react-loading-skeleton/dist/skeleton.css'
import {Providers} from "@/app/provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Driven License Learning',
    description: 'Generated by create next app',
}

export default function AuthenticateLayout({
                                           children,
                                       }: {
    children: React.ReactNode
}) {
    return (
            <div>
                {children}
            </div>
    )
}
